version: "3.8"

services:
    api-dev:
        build: .
        image: sdpx-api
        container_name: api-dev
        ports:
            - "8081:5000"
        links:
            - dev-mysql
        depends_on:
            - dev-mysql
        environment:
            MYSQL_HOST: dev-mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: db_dev

    api-test:
        image: sdpx-api
        container_name: api-test
        ports:
            - "8082:5000"
        links:
            - test-mysql
        depends_on:
            - test-mysql
        environment:
            MYSQL_HOST: test-mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: db_test

    dev-mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: db-dev
        ports:
          - "7000:3306"
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: db_dev
          MYSQL_USER: admin
          MYSQL_PASSWORD: db4dev$
        volumes:
            - ./db_dev/dev_data:/lib/var/mysql
            - ./db_dev/init.sql:/docker-entrypoint-initdb.d/init.sql

    test-mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: db-test
        ports:
          - "7001:3306"
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: db_test
          MYSQL_USER: admin
          MYSQL_PASSWORD: db4test$
        volumes:
            - ./db_test/test_data:/lib/var/mysql
            - ./db_test/init.sql:/docker-entrypoint-initdb.d/init.sql

